import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Container from "@/components/common/Container";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={archivo.className}>
      <body className="bg-black text-white">
        <Container>{children}</Container>
        
      </body>
    </html>
  );
}
